In [1]:
# To prevent the annoying warnings

import warnings 
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
dataframe = pd.read_csv('Data/After_Feature_Engineering.csv')

In [4]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97212 entries, 0 to 97211
Data columns (total 60 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Age                                   97212 non-null  float64
 1   Annual_Income                         97212 non-null  float64
 2   Monthly_Inhand_Salary                 97212 non-null  float64
 3   Num_Bank_Accounts                     97212 non-null  float64
 4   Num_Credit_Card                       97212 non-null  float64
 5   Interest_Rate                         97212 non-null  float64
 6   Num_of_Loan                           97212 non-null  float64
 7   Delay_from_due_date                   97212 non-null  int64  
 8   Num_of_Delayed_Payment                97212 non-null  float64
 9   Changed_Credit_Limit                  97212 non-null  float64
 10  Num_Credit_Inquiries                  97212 non-null  float64
 11  Credit_Mix     

In [5]:
from sklearn.model_selection import train_test_split

X = dataframe.drop(columns=['Credit_Score']).values
y = dataframe['Credit_Score'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=101)

In [6]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

prediction = model.predict(X_test)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.88      0.92      0.90     16663
           1       0.83      0.79      0.81     11439
           2       0.78      0.75      0.76      5923

    accuracy                           0.84     34025
   macro avg       0.83      0.82      0.82     34025
weighted avg       0.84      0.84      0.84     34025



In [8]:
print(confusion_matrix(y_test, prediction))

[[15266   982   415]
 [ 1577  9038   824]
 [  597   890  4436]]
